# 1016 attack config
attack:
  erase:
    iou_thresh: 0.5
    padding_type: mode
    do_erase: True
  shift:
    att_layer: [0]
    bbox_num: max
    n_att: 1
    shift_length: 4
    shift_direction: random
    padding_type: mode
  pgd:
    eps: [1.5,1.5,0]
    alpha: [0.05, 0.05, 0.05] 
    steps: 80
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: True
  save_path: 'save_attack/1016_erase_and_shift_and_pgd_'
  attack_target: pred
  loss_type: _1202_ESP
