# Basic attack config, use for basic debug
attack:
  shift:
    bbox_num: max
    n_att: 1
    shift_length: 4
    shift_direction: random
    padding_type: around
  attack_target: pred
  save_path: '/GPFS/data/shengyin/OpencoodV2-Main/OpenCOODv2/save_attack/shift_single_agent'
  loss_type: real_new_modified