# Basic attack config, use for basic debug
attack:
  pgd:
    eps: 0.6
    alpha: 0.12
    steps: 20
    n_att: 1
    attack_mode: others
    project: True
    keep_sparsity: True
    keep_pos: True
    colla_attack: True
    noise_attack: False
    vis_path: null
  attack_target: pred

