# Basic attack config, use for basic debug
attack:
  pgd:
    eps: 0.2
    alpha: 0.2
    steps: 1
    n_att: 2
    attack_mode: others
    project: True
    colla_attack: False
    noise_attack: False
    vis_path: null
  # attack_target: pred
  attack_target: gt

