# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [5,5,0]
    alpha: [0.167, 0.167, 0.167] 
    steps: 80
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: False
  save_path: 'save_attack/0311_PGD'
  attack_target: pred
  loss_type: _0311_PGD
  attack_type: pgd
