# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [10,10,0]
    alpha: [0.333, 0.333, 0.333] 
    steps: 80
    project: True
    colla_attack: False
    noise_attack: False
  n_att: 1
  save_attack: True
  save_path: 'save_attack/0311_PGD'
  attack_target: pred
  loss_type: _0311_PGD
  attack_type: pgd
