# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [1.5,1.5,0]
    alpha: [0.05, 0.05, 0.05] 
    steps: 80
    project: True
    colla_attack: False
    noise_attack: False
  n_att: 1
  save_attack: False
  save_path: 'save_attack/0223_PGD'
  attack_target: pred
  loss_type: _0223_PGD
  attack_type: pgd
