# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [2,2,0]
    alpha: [0.067, 0.067, 0.067] 
    steps: 80
    project: True
    colla_attack: False
    noise_attack: False
  n_att: 1
  save_attack: False
  save_path: 'save_attack/0312_PGD'
  attack_target: pred
  loss_type: _0312_PGD
  attack_type: pgd
