attack:
  pgd:
    eps: 0.5
    alpha: 0.1
    steps: 20
    n_att: 3
    attack_mode: others
    project: True
    keep_sparsity: True
    keep_pos: True
    colla_attack: True
    noise_attack: False
    vis_path: null
  attack_target: pred