# Basic attack config, use for basic debug
attack:
  erase:
    iou_thresh: 0.5
    padding_type: mode
    do_erase: False
  shift:
    att_layer: [0]
    bbox_num: max
    n_att: 1
    shift_length: 4
    shift_direction: random
    padding_type: mode
  save_path: '/GPFS/data/shengyin/OpencoodV2-Main/OpenCOODv2/save_attack/0712_erase_and_shift_single_agent'
  attack_target: pred
  loss_type: _shift_not_erase_0906
