# Basic attack config, use for basic debug
attack:
  pgd:
    eps: 0.3
    alpha: 0.06
    steps: 10
    n_att: 1
    attack_mode: others
    project: True
    keep_sparsity: True
    colla_attack: True
    noise_attack: False
    vis_path: null
  attack_target: pred
  # attack_target: gt

