# Basic attack config, use for basic debug
attack:
  shift:
    bbox_num: max
    n_att: 1
    shift_length: 4
    shift_direction: random
    padding_type: around
  pgd:
    eps: [0.1,0,0]
    alpha: 0.02
    steps: 10
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: True
  attack_target: pred
  save_path: '/GPFS/data/shengyin/OpenCOOD-main/save_attack/new_test_shift_and_pgd_single_agent'
  loss_type: real_new_modified
