# Basic attack config, use for basic debug
attack:
  pgd:
    eps: 0.5
    alpha: 0.1
    steps: 10
    n_att: 1
    attack_mode: others
    project: True
    colla_attack: True
    noise_attack: False
    vis_path: null
  attack_target: pred

