# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [10,0,0]
    alpha: 2
    steps: 20
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: True
  save_path: '/GPFS/data/shengyin/OpencoodV2-Main/OpenCOODv2/save_attack/single_agent/pgd_single_agent'
  attack_target: pred
  loss_type: 0605_attack
  # attack_target: gt

