# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [2,2,0]
    alpha: [0.06666666666666667, 0.06666666666666667, 0.06666666666666667] 
    steps: 80
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: True
  save_path: 'save_attack/1016_PGD'
  attack_target: pred
  loss_type: _1016_PGD
