# Basic attack config, use for basic debug
attack:
  pgd:
    eps: [0.15,0,0]
    alpha: 0.03
    steps: 10
    n_att: 1
    project: True
    colla_attack: False
    noise_attack: False
    save_attack: True
  save_path: '/GPFS/data/shengyin/OpenCOOD-main/save_attack/single_agent/pgd_single_agent'
  attack_target: gt
  loss_type: 0325_PGD
  # attack_target: gt

